Repository openfisca/openfisca-core, pull requests merged in 2018-11, with the labels that each got.

#761 Use branch name in CircleCI's cache identifier
  .circleci/config.yml
Labels: kind:devops

#756 Expose AmountTaxScale by Web API
  CHANGELOG.md
  openfisca_web_api/loader/parameters.py
  setup.py
  tests/web_api/loader/__init__.py
  tests/web_api/loader/test_parameters.py
Labels: flow:team:reviewing, kind:solution

#765 Add parameters in trace
  CHANGELOG.md
  openfisca_core/parameters.py
  openfisca_core/simulations.py
  openfisca_core/taxbenefitsystems.py
  openfisca_core/taxscales.py
  openfisca_core/tracers.py
  openfisca_web_api/openAPI.yml
  setup.py
  tests/core/test_simulations.py
  tests/core/test_tracer.py
Labels: flow:team:reviewing

#772 Cap PyTest version to avoid failures
  CHANGELOG.md
  setup.py
Labels: flow:team:expedite

#773 Cap all dependency versions
  CHANGELOG.md
  setup.py
Labels: kind:improvement

#767 Introduce ParameterNode.get_descendants
  CHANGELOG.md
  openfisca_core/parameters.py
  openfisca_web_api/loader/parameters.py
  setup.py
  tests/core/test_parameters.py
  tests/web_api/loader/test_parameters.py
Labels: flow:team:reviewing

#775 Fix amount scale parameters' access
  CHANGELOG.md
  openfisca_core/parameters.py
  setup.py
  tests/core/test_tax_scales.py
Labels: flow:team:reviewing

#776 Allow ParameterNode children to have a numeric keys
  CHANGELOG.md
  openfisca_core/parameters.py
  setup.py
  tests/core/test_parameters.py
Labels: flow:team:reviewing

#777 Don't impose log config
  CHANGELOG.md
  openfisca_core/__init__.py
  openfisca_core/scripts/__init__.py
  openfisca_core/tools/test_runner.py
  setup.py
Labels: flow:team:reviewing

#774 Deal with OverflowError
  CHANGELOG.md
  openfisca_core/entities.py
  setup.py
  tests/web_api/test_calculate.py
Labels: flow:team:reviewing
