Repository openfisca/openfisca-core, pull requests merged in 2018-03, with the labels that each got.

#618 Add swagger documentation for /spec endpoint
  CHANGELOG.md
  openfisca_web_api_preview/openAPI.yml
  setup.py
  tests/web_api/basic_case/test_spec.py
Labels: flow:contribution-backlog

#603 Improve tracer
  CHANGELOG.md
  openfisca_core/tracers.py
  openfisca_web_api_preview/openAPI.yml
  setup.py
Labels: flow:contribution-backlog

#621 Introduce new entities helper
  CHANGELOG.md
  openfisca_core/entities.py
  setup.py
  tests/core/test_entities.py
Labels: flow:team-backlog

#602 Improve projectors
  CHANGELOG.md
  openfisca_core/entities.py
  setup.py
  tests/core/test_entities.py
Labels: flow:contribution-backlog

#627 Update openfisca serve rst documentation
  CHANGELOG.md
  doc/source/openfisca_serve.rst
  setup.py
Labels: flow:team:doing, kind:documentation
