Repository openfisca/openfisca-core, pull requests merged in 2018-04, with the labels that each got.

#640 Bump country-template version to >=3.0.0, <4.0.0
  CHANGELOG.md
  openfisca_core/indexed_enums.py
  setup.py
  tests/web_api/basic_case/test_calculate.py
  tests/web_api/basic_case/test_variables.py
Labels: flow:team:doing, kind:improvement

#644 Improve parameters performances
  CHANGELOG.md
  openfisca_core/parameters.py
  setup.py
Labels: flow:contrib:backlog

#639 Update CircleCI configuration to its v2
  .circleci/config.yml
  CHANGELOG.md
  circle.yml
  setup.py
Labels: flow:team:doing, kind:devops

#647 Document how to run a specific test with nosetests
  README.md
Labels: flow:support:doing, kind:documentation

#649 Cache known hosts after checkout
  .circleci/config.yml
Labels: flow:team:doing, kind:bug, kind:devops

#654 Fix enum dtype
  CHANGELOG.md
  openfisca_core/indexed_enums.py
  openfisca_core/variables.py
  setup.py
  tests/core/test_holders.py
Labels: kind:bug

#648 Avoid collisions between module names
  CHANGELOG.md
  openfisca_core/taxbenefitsystems.py
  setup.py
Labels: kind:bug
