Repository openfisca/openfisca-core, pull requests merged in 2018-10, with the labels that each got.

#717 Add editorial content on parameter and variable
  .gitignore
  CHANGELOG.md
  openfisca_core/parameters.py
  openfisca_core/variables.py
  openfisca_web_api/loader/parameters.py
  openfisca_web_api/loader/variables.py
  setup.py
  tests/core/test_parameters.py
  tests/web_api/test_parameters.py
  tests/web_api/test_variables.py
Labels: flow:team:doing, kind:solution

#729 In Python, simplify simulation initialisation
  CHANGELOG.md
  openfisca_core/scripts/simulation_generator.py
  openfisca_core/simulations.py
  setup.py
  tests/core/test_calculate_output.py
Labels: kind:improvement

#734 Correct style ignore: W503 rather than W504
  CHANGELOG.md
  setup.cfg
  setup.py
  tests/web_api/test_entities.py
Labels: flow:team:doing, kind:improvement

#737 Fix type value for string variables
  CHANGELOG.md
  openfisca_core/variables.py
  setup.py
  tests/core/test_variables.py
  tests/web_api/test_trace.py
Labels: flow:team:reviewing, kind:bug

#742 Fix trace and calculate endpoints responses for str variables
  CHANGELOG.md
  openfisca_web_api/app.py
  setup.py
  tests/web_api/test_calculate.py
  tests/web_api/test_trace.py
Labels: flow:team:doing

#735 Apply PEP8 W504 (Knuth's Style)
  CHANGELOG.md
  openfisca_core/parameters.py
  openfisca_core/periods.py
  openfisca_core/scripts/measure_performances_fancy_indexing.py
  setup.py
Labels: flow:qualified-issues, kind:improvement, level:intermediate

#746 Use PyTest
  CHANGELOG.md
  Makefile
  setup.cfg
  setup.py
Labels: kind:improvement

#747 Do not format style before check
  .circleci/has-functional-changes.sh
  Makefile
Labels: kind:bug
