Repository openfisca/openfisca-core, pull requests merged in 2018-12, with the labels that each got.

#781 Uniformize tests with the new API
  .circleci/config.yml
  CHANGELOG.md
  openfisca_core/entities.py
  openfisca_core/errors.py
  openfisca_core/holders.py
  openfisca_core/indexed_enums.py
  openfisca_core/parameters.py
  openfisca_core/scenarios.py
  openfisca_core/scripts/migrations/v24_to_25.py
  openfisca_core/scripts/openfisca_command.py
  openfisca_core/scripts/run_test.py
  openfisca_core/simulation_builder.py
  openfisca_core/simulations.py
  openfisca_core/taxbenefitsystems.py
  openfisca_core/tools/__init__.py
  openfisca_core/tools/test_runner.py
  openfisca_web_api/app.py
  openfisca_web_api/handlers.py
  openfisca_web_api/scripts/serve.py
  setup.py
  tests/core/test_entities.py
  tests/core/test_extensions.py
  tests/core/test_extra_params.py
  tests/core/test_holders.py
  tests/core/test_simulation_builder.py
  tests/core/test_simulations.py
  tests/core/test_yaml.py
  tests/core/tools/__init__.py
  tests/core/tools/test_assert_near.py
  tests/core/yaml_tests/directory/subdirectory/test_4.yaml
  tests/core/yaml_tests/directory/test_1.yaml
  tests/core/yaml_tests/directory/test_2.yaml
  tests/core/yaml_tests/failing_test_absolute_error_margin.yaml
  tests/core/yaml_tests/failing_test_relative_error_margin.yaml
  tests/core/yaml_tests/test_absolute_error_margin.yaml
  tests/core/yaml_tests/test_failure.yaml
  tests/core/yaml_tests/test_name_filter.yaml
  tests/core/yaml_tests/test_relative_error_margin.yaml
  tests/core/yaml_tests/test_success.yaml
  tests/core/yaml_tests/test_with_anchors.yaml
  tests/core/yaml_tests/test_with_extension.yaml
  tests/core/yaml_tests/test_with_reform.yaml
  tests/core/yaml_tests/test_with_reform_2.yaml
  tests/web_api/test_calculate.py
  tests/web_api/test_variables.py
Labels: flow:team:reviewing

#787 Don't sort JSON keys in the Web API
  CHANGELOG.md
  openfisca_web_api/app.py
  setup.py
Labels: flow:team:reviewing

#793 Fix YAML indentation in CHANGELOG.md
  CHANGELOG.md
Labels: flow:team:reviewing, kind:improvement

#794 Explicit test runner dependencies in Python 2.7
  CHANGELOG.md
  setup.py
Labels: kind:bug

#766 Add support for DAY periods
  CHANGELOG.md
  openfisca_core/model_api.py
  openfisca_core/periods.py
  openfisca_core/simulations.py
  openfisca_core/variables.py
  setup.py
  tests/core/test_periods.py
Labels: flow:team:reviewing, kind:solution
