Repository openfisca/openfisca-core, pull requests merged in 2018-07, with the labels that each got.

#686 Update psutil version to 5.4.6
  CHANGELOG.md
  setup.py
Labels: flow:team:doing

#689 Introduce TaxBenefitSystem.replace_variable
  CHANGELOG.md
  openfisca_core/taxbenefitsystems.py
  setup.py
  tests/core/test_reforms.py
Labels: kind:solution

#681 Parse parameters metadata and expose them in Python
  .circleci/config.yml
  CHANGELOG.md
  openfisca_core/parameters.py
  setup.py
  tests/core/test_parameters.py
Labels: flow:contrib:doing
