Repository openfisca/openfisca-core, pull requests merged in 2019-02, with the labels that each got.

#811 Introduce LookupTaxScale
  CHANGELOG.md
  openfisca_core/parameters.py
  openfisca_core/taxscales.py
  setup.py
  tests/core/test_tax_scales.py
Labels: flow:reviewing, in progress

#820 Fix message output by test runner when a variable is unknown
  CHANGELOG.md
  openfisca_core/errors.py
  openfisca_core/simulations.py
  openfisca_core/tools/test_runner.py
  setup.py
  tests/core/test_runner/test_yaml_runner.py
  tests/core/test_simulations.py
Labels: in progress

#821 Add debugger option to openfisca test
  CHANGELOG.md
  openfisca_core/scripts/openfisca_command.py
  openfisca_core/scripts/run_test.py
  openfisca_core/taxscales.py
  openfisca_core/tools/test_runner.py
  setup.py
Labels: flow:reviewing

#827 Optimize set_input_dispatch_by_period
  CHANGELOG.md
  openfisca_core/holders.py
  setup.py
  tests/core/test_holders.py
Labels: flow:delivery, in progress

#790 Improve design and test coverage of complex simulation construction
  CHANGELOG.md
  openfisca_core/columns.py
  openfisca_core/conv.py
  openfisca_core/decompositions.py
  openfisca_core/decompositionsxml.py
  openfisca_core/entities.py
  openfisca_core/holders.py
  openfisca_core/json_to_test_case.py
  openfisca_core/periods.py
  openfisca_core/reforms.py
  openfisca_core/scenarios.py
  openfisca_core/scripts/json_with_test_case_to_input_variables.py
  openfisca_core/scripts/measure_performances.py
  openfisca_core/scripts/simulation_generator.py
  openfisca_core/simulation_builder.py
  openfisca_core/simulations.py
  openfisca_core/taxbenefitsystems.py
  openfisca_core/tools/simulation_dumper.py
  openfisca_core/tools/test_runner.py
  openfisca_core/variables.py
  setup.py
  tests/core/test_axes.py
  tests/core/test_columns.py
  tests/core/test_dump_restore.py
  tests/core/test_entities.py
  tests/core/test_json_to_test_case.py
  tests/core/test_scenarios.py
  tests/core/test_simulation_builder.py
  tests/web_api/test_calculate.py
Labels: kind:solution, level:advanced

#831 Add badges to README.md
  CHANGELOG.md
  README.md
  setup.py
Labels: flow:qualified-issues, in progress, kind:com, level:starter

#830 Add test coverage
  .circleci/config.yml
  CHANGELOG.md
  setup.cfg
  setup.py
Labels: flow:qualified-issues, in progress, kind:improvement, level:starter
