Repository openfisca/openfisca-core, pull requests merged in 2019-03, with the labels that each got.

#825 Fix regression on YAML tests runner cache for tax benefit systems with reforms or extensions
  CHANGELOG.md
  openfisca_core/tools/test_runner.py
  setup.py
  tests/core/test_runner/test_yaml_runner.py
  tests/core/tools/test_runner/test_yaml_runner.py
Labels: flow:re-reviewing, kind:bug

#829 Update autopep8 and flake8
  CHANGELOG.md
  openfisca_core/periods.py
  openfisca_core/scripts/remove_fuzzy.py
  setup.cfg
  setup.py
  tests/core/parameters_fancy_indexing/test_fancy_indexing.py
  tests/web_api/test_parameters.py
  tests/web_api/test_variables.py
Labels: in progress, kind:improvement, level:starter

#836 Convert tests that were incompatible with Pytest 4.0+
  CHANGELOG.md
  setup.py
  tests/core/parameter_validation/test_parameter_validation.py
  tests/core/test_periods.py
  tests/core/test_reforms.py
  tests/core/test_tracer.py
  tests/web_api/test_calculate.py
  tests/web_api/test_parameters.py
  tests/web_api/test_variables.py
Labels: in progress

#835 Relax rules on allocation to group entities
  CHANGELOG.md
  openfisca_core/simulation_builder.py
  setup.py
  tests/core/test_simulation_builder.py
  tests/web_api/test_calculate.py
Labels: in progress

#833 Build simulation with tabular inputs
  CHANGELOG.md
  openfisca_core/entities.py
  openfisca_core/simulation_builder.py
  openfisca_core/simulations.py
  openfisca_core/taxbenefitsystems.py
  setup.py
  tests/core/test_simulation_builder.py
Labels: in progress

#826 Fix end date application
  CHANGELOG.md
  openfisca_core/holders.py
  openfisca_core/simulation_builder.py
  openfisca_core/simulations.py
  setup.py
  tests/core/test_variables.py
Labels: flow:re-reviewing, in progress

#839 Restrict some Pytest options to 'make test', not all Pytest runs
  .circleci/config.yml
  CHANGELOG.md
  Makefile
  setup.cfg
  setup.py
Labels: flow:reviewing, in progress

#844 Fix end date comparison
  CHANGELOG.md
  openfisca_core/simulation_builder.py
  setup.py
  tests/core/yaml_tests/test_success.yaml
Labels: in progress

#847 Remove extra_params altogether from Core
  CHANGELOG.md
  openfisca_core/base_functions.py
  openfisca_core/data_storage.py
  openfisca_core/holders.py
  openfisca_core/simulations.py
  openfisca_core/tracers.py
  setup.py
  tests/core/test_extra_params.py
  tests/core/test_holders.py
Labels: flow:delivery, in progress

#845 Always use safe_load to load YAML data
  CHANGELOG.md
  openfisca_core/scripts/migrations/v24_to_25.py
  openfisca_core/tools/test_runner.py
  openfisca_web_api/loader/spec.py
  setup.py
  tests/core/test_axes.py
  tests/core/test_entities.py
  tests/core/test_simulation_builder.py
Labels: flow:delivery, in progress

#843 Remove simulation_json argument to Simulation constructor
  CHANGELOG.md
  openfisca_core/simulation_builder.py
  openfisca_core/simulations.py
  openfisca_core/taxbenefitsystems.py
  openfisca_core/tools/simulation_dumper.py
  openfisca_core/tools/test_runner.py
  openfisca_web_api/handlers.py
  setup.py
  tests/core/test_base_functions.py
  tests/core/test_calculate_output.py
  tests/core/test_countries.py
  tests/core/test_cycles.py
  tests/core/test_dump_restore.py
  tests/core/test_formulas.py
  tests/core/test_holders.py
  tests/core/test_opt_out_cache.py
  tests/core/test_reforms.py
  tests/core/test_simulation_builder.py
  tests/core/test_simulations.py
  tests/core/test_variables.py
Labels: flow:qualified-issues, in progress

#852 Remove stray print statements
  CHANGELOG.md
  openfisca_core/scripts/find_placeholders.py
  openfisca_core/scripts/measure_numpy_condition_notations.py
  openfisca_core/scripts/measure_performances.py
  openfisca_core/scripts/measure_performances_fancy_indexing.py
  openfisca_core/scripts/migrations/v16_2_to_v17/xml_to_yaml.py
  openfisca_core/scripts/migrations/v24_to_25.py
  openfisca_core/simulations.py
  openfisca_core/tools/test_runner.py
  openfisca_core/tracers.py
  setup.py
Labels: in progress

#858 Fix AttributeError on simulation
  CHANGELOG.md
  openfisca_core/simulations.py
  setup.py
Labels: flow:reviewing, in progress

#817 Ensure consistent results in the presence of "spirals"
  CHANGELOG.md
  openfisca_core/simulations.py
  openfisca_core/tracers.py
  setup.py
  tests/core/test_cycles.py
Labels: flow:discovery

#855 Remove Python 2 compatibility code
  CHANGELOG.md
  openfisca_core/commons.py
  openfisca_core/errors.py
  openfisca_core/parameters.py
  openfisca_core/periods.py
  openfisca_core/reforms.py
  openfisca_core/scripts/measure_numpy_condition_notations.py
  openfisca_core/scripts/migrations/v16_2_to_v17/xml_to_yaml.py
  openfisca_core/simulation_builder.py
  openfisca_core/taxbenefitsystems.py
  openfisca_core/tools/__init__.py
  openfisca_core/tools/test_runner.py
  openfisca_core/variables.py
  openfisca_web_api/app.py
  openfisca_web_api/handlers.py
  openfisca_web_api/loader/entities.py
  openfisca_web_api/loader/variables.py
  setup.py
  tests/core/test_periods.py
  tests/web_api/test_calculate.py
  tests/web_api/test_entities.py
Labels: in progress
