Repository openfisca/openfisca-core, pull requests merged in 2019-01, with the labels that each got.

#802 Load extensions more reliably
  CHANGELOG.md
  openfisca_core/taxbenefitsystems.py
  setup.py
Labels: kind:bug, level:intermediate

#809 Build only Python 3 version
  .circleci/config.yml
Labels: flow:expedite, in progress

#815 Move docstring
  CHANGELOG.md
  openfisca_core/tracers.py
  setup.py
Labels: flow:reviewing, in progress

#814 Ensure correct period is given in failing test help messages
  CHANGELOG.md
  openfisca_core/tools/test_runner.py
  setup.py
Labels: flow:reviewing, in progress
