Repository openfisca/openfisca-core, pull requests merged in 2019-04, with the labels that each got.

#860 Apply general spring style formatting 🌻
  CHANGELOG.md
  openfisca_core/entities.py
  openfisca_core/simulation_builder.py
  openfisca_core/simulations.py
  openfisca_core/tools/test_runner.py
  openfisca_web_api/handlers.py
  setup.py
  tests/core/test_yaml.py
Labels: flow:re-reviewing, in progress, kind:improvement, level:starter

#859 Do not ignore inputs for several months or years
  CHANGELOG.md
  openfisca_core/holders.py
  setup.py
  tests/core/test_holders.py
  tests/core/test_parameters.py
  tests/web_api/case_with_extension/test_extensions.py
  tests/web_api/test_calculate.py
  tests/web_api/test_entities.py
  tests/web_api/test_headers.py
  tests/web_api/test_helpers.py
  tests/web_api/test_parameters.py
  tests/web_api/test_spec.py
  tests/web_api/test_trace.py
  tests/web_api/test_variables.py
Labels: in progress

#813 Remove base functions
  CHANGELOG.md
  openfisca_core/base_functions.py
  openfisca_core/model_api.py
  openfisca_core/simulations.py
  openfisca_core/variables.py
  setup.py
  tests/core/test_base_functions.py
  tests/core/test_reforms.py
Labels: in progress

#840 Improve usability of Enum values
  CHANGELOG.md
  openfisca_core/indexed_enums.py
  openfisca_core/simulations.py
  setup.py
  tests/core/test_holders.py
Labels: flow:reviewing, in progress

#857 Distinguish population-level from model-level abstractions
  CHANGELOG.md
  openfisca_core/entities.py
  openfisca_core/holders.py
  openfisca_core/model_api.py
  openfisca_core/populations.py
  openfisca_core/reforms.py
  openfisca_core/scripts/measure_performances.py
  openfisca_core/scripts/simulation_generator.py
  openfisca_core/simulation_builder.py
  openfisca_core/simulations.py
  openfisca_core/taxbenefitsystems.py
  openfisca_core/tools/simulation_dumper.py
  openfisca_core/tools/test_runner.py
  openfisca_core/variables.py
  openfisca_web_api/handlers.py
  setup.py
  tests/core/test_countries.py
  tests/core/test_entities.py
  tests/core/test_formulas.py
  tests/core/test_reforms.py
  tests/core/test_simulation_builder.py
  tests/core/test_simulations.py
  tests/core/tools/test_runner/test_yaml_runner.py
Labels: flow:re-reviewing, in progress

#863 Display symbolic values of Enums in /trace and print_computation_log
  CHANGELOG.md
  openfisca_core/indexed_enums.py
  openfisca_web_api/handlers.py
  setup.py
  tests/core/test_tracer.py
  tests/web_api/test_trace.py
Labels: in progress

#864 Fix swagger host
  CHANGELOG.md
  openfisca_web_api/app.py
  setup.py
  tests/web_api/test_spec.py
Labels: in progress

#866 Raise an error when keys are duplicated in parameters files
  CHANGELOG.md
  openfisca_core/parameters.py
  setup.py
  tests/core/parameter_validation/duplicate_key.yaml
  tests/core/parameter_validation/test_parameter_validation.py
  tests/core/parameters_fancy_indexing/test_fancy_indexing.py
Labels: flow:reviewing, in progress

#865 Improve error messages for entity role issues
  CHANGELOG.md
  openfisca_core/simulation_builder.py
  openfisca_core/tools/test_runner.py
  setup.py
  tests/web_api/test_calculate.py
Labels: in progress

#867 Use Pytest in the test runner
  CHANGELOG.md
  README.md
  openfisca_core/errors.py
  openfisca_core/holders.py
  openfisca_core/periods.py
  openfisca_core/scripts/measure_numpy_condition_notations.py
  openfisca_core/scripts/run_test.py
  openfisca_core/simulations.py
  openfisca_core/taxbenefitsystems.py
  openfisca_core/tools/test_runner.py
  openfisca_core/tracers.py
  openfisca_core/variables.py
  setup.cfg
  setup.py
  tests/core/parameters_fancy_indexing/test_fancy_indexing.py
  tests/core/test_extensions.py
  tests/core/test_formula_helpers.py
  tests/core/test_parameters.py
  tests/core/test_variables.py
  tests/core/test_yaml.py
  tests/core/tools/test_runner/test_yaml_runner.py
  tests/core/yaml_tests/test_name_filter.yaml
  tests/web_api/test_entities.py
  tests/web_api/test_parameters.py
  tests/web_api/test_spec.py
  tests/web_api/test_trace.py
  tests/web_api/test_variables.py
Labels: in progress
