Repository openfisca/openfisca-core, pull requests merged in 2021-04, with the labels that each got.

#993 Gracefully handle unexpected errors
  CHANGELOG.md
  openfisca_web_api/app.py
  setup.py
  tests/web_api/test_calculate.py
Labels: kind:bug

#994 In SimulationBuilder, repair expansion of axes on a variable given as input
  CHANGELOG.md
  openfisca_core/simulations/simulation_builder.py
  setup.py
  tests/core/test_axes.py
Labels: kind:bug

#999 Change log.warning to warnings.warn to allow users of the package to hide them.
  CHANGELOG.md
  openfisca_core/experimental/memory_config.py
  openfisca_core/parameters/config.py
  openfisca_core/simulations/simulation.py
  openfisca_core/tools/test_runner.py
  openfisca_core/warnings/__init__.py
  openfisca_core/warnings/libyaml_warning.py
  openfisca_core/warnings/memory_warning.py
  openfisca_core/warnings/tempfile_warning.py
  setup.py
Labels: kind:improvement

#997 Make CountryTaxBenefitSystem reusable as a fixture
  CHANGELOG.md
  README.md
  STYLEGUIDE.md
  conftest.py
  setup.py
  tests/__init__.py
  tests/core/parameter_validation/test_parameter_clone.py
  tests/core/test_axes.py
  tests/core/test_calculate_output.py
  tests/core/test_countries.py
  tests/core/test_cycles.py
  tests/core/test_dump_restore.py
  tests/core/test_entities.py
  tests/core/test_extensions.py
  tests/core/test_formulas.py
  tests/core/test_holders.py
  tests/core/test_opt_out_cache.py
  tests/core/test_parameters.py
  tests/core/test_reforms.py
  tests/core/test_simulation_builder.py
  tests/core/test_simulations.py
  tests/core/test_yaml.py
  tests/core/tools/test_assert_near.py
  tests/fixtures/__init__.py
  tests/fixtures/entities.py
  tests/fixtures/simulations.py
  tests/fixtures/taxbenefitsystems.py
  tests/fixtures/variables.py
Labels: kind:improvement

#984 Refactor web_api test using pytest.fixtures
  CHANGELOG.md
  conftest.py
  setup.py
  tests/fixtures/appclient.py
  tests/web_api/__init__.py
  tests/web_api/test_calculate.py
  tests/web_api/test_entities.py
  tests/web_api/test_headers.py
  tests/web_api/test_helpers.py
  tests/web_api/test_parameters.py
  tests/web_api/test_spec.py
  tests/web_api/test_trace.py
  tests/web_api/test_variables.py
Labels: kind:improvement

#990 Upgrade numpy to add support for M1 processors
  CHANGELOG.md
  openfisca_core/indexed_enums/enum.py
  openfisca_core/indexed_enums/enum_array.py
  openfisca_core/taxscales/abstract_rate_tax_scale.py
  openfisca_core/taxscales/abstract_tax_scale.py
  openfisca_core/taxscales/amount_tax_scale_like.py
  openfisca_core/taxscales/helpers.py
  openfisca_core/taxscales/linear_average_rate_tax_scale.py
  openfisca_core/taxscales/marginal_amount_tax_scale.py
  openfisca_core/taxscales/marginal_rate_tax_scale.py
  openfisca_core/taxscales/rate_tax_scale_like.py
  openfisca_core/taxscales/single_amount_tax_scale.py
  openfisca_core/taxscales/tax_scale_like.py
  openfisca_core/tracers/computation_log.py
  openfisca_core/tracers/flat_trace.py
  openfisca_core/tracers/full_tracer.py
  openfisca_core/tracers/performance_log.py
  openfisca_core/tracers/simple_tracer.py
  openfisca_core/tracers/trace_node.py
  openfisca_core/tracers/tracing_parameter_node_at_instant.py
  openfisca_core/variables/config.py
  setup.py
Labels: kind:dependencies

#1014 Drop latest NumPy supported version to 1.18.x
  CHANGELOG.md
  openfisca_core/indexed_enums/enum.py
  openfisca_core/indexed_enums/enum_array.py
  openfisca_core/taxscales/abstract_rate_tax_scale.py
  openfisca_core/taxscales/abstract_tax_scale.py
  openfisca_core/taxscales/amount_tax_scale_like.py
  openfisca_core/taxscales/helpers.py
  openfisca_core/taxscales/linear_average_rate_tax_scale.py
  openfisca_core/taxscales/marginal_amount_tax_scale.py
  openfisca_core/taxscales/marginal_rate_tax_scale.py
  openfisca_core/taxscales/rate_tax_scale_like.py
  openfisca_core/taxscales/single_amount_tax_scale.py
  openfisca_core/taxscales/tax_scale_like.py
  openfisca_core/tracers/computation_log.py
  openfisca_core/tracers/flat_trace.py
  openfisca_core/tracers/full_tracer.py
  openfisca_core/tracers/performance_log.py
  openfisca_core/tracers/simple_tracer.py
  openfisca_core/tracers/trace_node.py
  openfisca_core/tracers/tracing_parameter_node_at_instant.py
  openfisca_core/variables/config.py
  setup.py
Labels: kind:bug
