Repository openfisca/openfisca-core, pull requests merged in 2022-11, with the labels that each got.

#1143 Re-add support for dispatch/divide by days
  CHANGELOG.md
  openfisca_core/holders/helpers.py
  openfisca_core/holders/tests/test_helpers.py
  setup.cfg
  setup.py
Labels: kind:solution

#1149 Introduce error margin by variable in tests
  CHANGELOG.md
  openfisca_core/tools/test_runner.py
  setup.py
  tests/fixtures/yaml_tests/failing_test_absolute_error_margin.yaml
  tests/fixtures/yaml_tests/failing_test_relative_error_margin.yaml
  tests/fixtures/yaml_tests/test_absolute_error_margin.yaml
  tests/fixtures/yaml_tests/test_relative_error_margin.yaml
Labels: meta:user-experience, contrib:ipp, type:contrib

#1165 Fix documentation
  CHANGELOG.md
  openfisca_core/simulations/simulation.py
  openfisca_core/taxbenefitsystems/tax_benefit_system.py
  openfisca_core/tools/test_runner.py
  openfisca_core/types/__init__.py
  openfisca_core/types/_domain.py
  openfisca_core/variables/__init__.py
  openfisca_core/variables/typing.py
  openfisca_core/variables/variable.py
  openfisca_tasks/install.mk
  setup.py
Labels: kind:bug, level:starter

#1166 Fix Holder's doctests
  CHANGELOG.md
  openfisca_core/holders/__init__.py
  openfisca_core/holders/holder.py
  openfisca_core/holders/memory_usage.py
  openfisca_core/populations/population.py
  openfisca_core/types/_domain.py
  openfisca_tasks/install.mk
  openfisca_tasks/test_code.mk
  setup.cfg
  setup.py
Labels: kind:bug, level:starter
