Repository openfisca/openfisca-core, pull requests merged in 2022-12, with the labels that each got.

#1160 Remove constraint on packages
  .github/workflows/workflow.yml
  .gitignore
  CHANGELOG.md
  README.md
  openfisca_tasks/install.mk
  openfisca_tasks/publish.mk
  openfisca_tasks/test_code.mk
  setup.py
Labels: kind:dependencies

#1142 Deprecate Instant.period
  CHANGELOG.md
  openfisca_core/holders/helpers.py
  openfisca_core/periods/__init__.py
  openfisca_core/periods/helpers.py
  openfisca_core/periods/instant_.py
  openfisca_core/periods/period_.py
  setup.py
Labels: kind:improvement

#1169 Unify casing of NumPy
  CHANGELOG.md
  openfisca_core/commons/tests/test_formulas.py
  openfisca_core/indexed_enums/enum_array.py
  openfisca_core/variables/variable.py
  setup.py
Labels: level:starter, kind:improvement

#1170 Always import numpy
  CHANGELOG.md
  openfisca_core/scripts/measure_numpy_condition_notations.py
  openfisca_core/scripts/measure_performances.py
  openfisca_core/scripts/measure_performances_fancy_indexing.py
  openfisca_core/scripts/remove_fuzzy.py
  openfisca_core/scripts/simulation_generator.py
  openfisca_core/tools/__init__.py
  openfisca_core/tools/simulation_dumper.py
  setup.py
  tests/core/parameters_fancy_indexing/test_fancy_indexing.py
  tests/core/test_projectors.py
  tests/core/test_tracers.py
  tests/core/tools/test_assert_near.py
  tests/core/tools/test_runner/test_yaml_runner.py
  tests/core/variables/test_annualize.py
Labels: level:starter, kind:improvement

#989 Upgrade OpenAPI spec to v3
  CHANGELOG.md
  openfisca_web_api/app.py
  openfisca_web_api/loader/spec.py
  openfisca_web_api/openAPI.yml
  setup.py
  tests/web_api/test_spec.py
Labels: kind:solution
