Repository openfisca/openfisca-core, pull requests merged in 2024-10, with the labels that each got.

#1253 docs(entities): fix docs
  CHANGELOG.md
  openfisca_core/commons/__init__.py
  openfisca_core/commons/formulas.py
  openfisca_core/commons/misc.py
  openfisca_core/commons/rates.py
  openfisca_core/entities/_core_entity.py
  openfisca_core/entities/_description.py
  openfisca_core/entities/entity.py
  openfisca_core/entities/group_entity.py
  openfisca_core/entities/helpers.py
  openfisca_core/entities/role.py
  openfisca_core/entities/tests/test_role.py
  openfisca_core/periods/helpers.py
  openfisca_core/simulations/simulation_builder.py
  setup.cfg
  setup.py
Labels: kind:docs

#1256 docs(commons): fix bad indent
  CHANGELOG.md
  openfisca_core/commons/formulas.py
  setup.py
Labels: kind:docs

#1257 ci: add matrix & fix conda
  .conda/openfisca-core/conda_build_config.yaml
  .conda/openfisca-core/meta.yaml
  .conda/openfisca-country-template/recipe.yaml
  .conda/openfisca-country-template/variants.yaml
  .conda/openfisca-extension-template/recipe.yaml
  .conda/openfisca-extension-template/variants.yaml
  .conda/pylint-per-file-ignores/recipe.yaml
  .conda/pylint-per-file-ignores/variants.yaml
  .github/get_pypi_info.py
  .github/workflows/_before-conda.yaml
  .github/workflows/_before-pip.yaml
  .github/workflows/_lint-pip.yaml
  .github/workflows/_test-conda.yaml
  .github/workflows/_test-pip.yaml
  .github/workflows/_version.yaml
  .github/workflows/merge.yaml
  .github/workflows/push.yaml
  CHANGELOG.md
  openfisca_core/commons/formulas.py
  openfisca_core/commons/rates.py
  openfisca_core/commons/tests/test_dummy.py
  openfisca_core/commons/tests/test_formulas.py
  openfisca_core/commons/tests/test_rates.py
  pyproject.toml
  setup.py
Labels: kind:ci

#1258 ci: fix deploy to PyPi
  .github/workflows/merge.yaml
  openfisca_tasks/publish.mk
Labels: kind:ci

#1261 test(storage): fix data_storage doctest
  CHANGELOG.md
  openfisca_core/data_storage/in_memory_storage.py
  openfisca_core/data_storage/on_disk_storage.py
  openfisca_tasks/test_code.mk
  setup.py
Labels: kind:test

#1263 docs(storage): fix data_storage docs
  CHANGELOG.md
  openfisca_core/data_storage/in_memory_storage.py
  openfisca_core/data_storage/on_disk_storage.py
  openfisca_tasks/lint.mk
  setup.py
Labels: kind:docs

#1264 docs(storage): fix data_storage types
  .conda/openfisca-core/meta.yaml
  .github/workflows/_before-conda.yaml
  .github/workflows/merge.yaml
  CHANGELOG.md
  openfisca_core/data_storage/__init__.py
  openfisca_core/data_storage/in_memory_storage.py
  openfisca_core/data_storage/on_disk_storage.py
  openfisca_core/data_storage/types.py
  openfisca_core/indexed_enums/enum.py
  openfisca_core/indexed_enums/enum_array.py
  openfisca_core/indexed_enums/types.py
  openfisca_core/types.py
  openfisca_tasks/lint.mk
  setup.py
Labels: kind:docs

#1255 test(entities): fix doctests
  CHANGELOG.md
  openfisca_core/entities/__init__.py
  openfisca_core/entities/_core_entity.py
  openfisca_core/entities/_description.py
  openfisca_core/entities/entity.py
  openfisca_core/entities/group_entity.py
  openfisca_core/entities/helpers.py
  openfisca_core/entities/role.py
  setup.cfg
  setup.py
Labels: kind:test

#1282 build: add spell check
  .conda/openfisca-country-template/recipe.yaml
  .conda/openfisca-extension-template/recipe.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  README.md
  STYLEGUIDE.md
  openfisca_core/commons/formulas.py
  openfisca_core/entities/_core_entity.py
  openfisca_core/parameters/parameter_node_at_instant.py
  openfisca_core/parameters/vectorial_parameter_node_at_instant.py
  openfisca_core/populations/group_population.py
  openfisca_core/projectors/helpers.py
  openfisca_core/simulations/simulation.py
  openfisca_core/taxbenefitsystems/tax_benefit_system.py
  openfisca_tasks/lint.mk
  pyproject.toml
  setup.py
  tests/core/variables/test_variables.py
  tests/fixtures/yaml_tests/test_name_filter.yaml
  tests/web_api/test_calculate.py
  tests/web_api/test_variables.py
Labels: kind:build

#1275 docs(experimental): add docs
  CHANGELOG.md
  openfisca_core/experimental/__init__.py
  openfisca_core/experimental/_errors.py
  openfisca_core/experimental/_memory_config.py
  openfisca_core/experimental/memory_config.py
  openfisca_core/tools/test_runner.py
  openfisca_core/warnings/__init__.py
  openfisca_tasks/lint.mk
  openfisca_tasks/test_code.mk
  openfisca_web_api/handlers.py
  setup.cfg
  setup.py
  tests/core/test_holders.py
  tests/core/variables/test_variables.py
Labels: kind:docs

#1279 feat: add core population
  CHANGELOG.md
  openfisca_core/holders/__init__.py
  openfisca_core/holders/holder.py
  openfisca_core/holders/memory_usage.py
  openfisca_core/holders/types.py
  openfisca_core/populations/__init__.py
  openfisca_core/populations/_core_population.py
  openfisca_core/populations/_errors.py
  openfisca_core/populations/config.py
  openfisca_core/populations/group_population.py
  openfisca_core/populations/population.py
  openfisca_core/populations/types.py
  openfisca_core/types.py
  openfisca_tasks/lint.mk
  setup.py
Labels: kind:feat

#1283 build: remove coveralls
  .github/workflows/_test-pip.yaml
  .gitignore
  CHANGELOG.md
  README.md
  openfisca_core/data_storage/in_memory_storage.py
  openfisca_core/data_storage/on_disk_storage.py
  openfisca_core/holders/holder.py
  openfisca_tasks/test_code.mk
  setup.cfg
  setup.py
  tests/core/test_yaml.py
  tests/web_api/test_parameters.py
  tests/web_api/test_variables.py
Labels: kind:build

#1280 docs: add types to tracers (1/3)
  CHANGELOG.md
  openfisca_core/populations/_errors.py
  openfisca_core/populations/types.py
  openfisca_core/tracers/__init__.py
  openfisca_core/tracers/computation_log.py
  openfisca_core/tracers/flat_trace.py
  openfisca_core/tracers/full_tracer.py
  openfisca_core/tracers/simple_tracer.py
  openfisca_core/tracers/trace_node.py
  openfisca_core/tracers/types.py
  openfisca_core/types.py
  setup.py
Labels: kind:docs
