Repository openfisca/openfisca-core, pull requests merged in 2025-03, with the labels that each got.

#1322 build: fix conda numpy version
  .conda/openfisca-core/conda_build_config.yaml
  .conda/openfisca-core/meta.yaml
  .conda/openfisca-country-template/recipe.yaml
  CHANGELOG.md
  openfisca_core/indexed_enums/_utils.py
  setup.py
Labels: kind:build

#1304 revert: restore line printing in tracer
  CHANGELOG.md
  openfisca_core/tracers/computation_log.py
  setup.py
Labels: kind:fix

#1323 test: adapt to country-template v8
  .conda/openfisca-country-template/recipe.yaml
  .conda/openfisca-extension-template/recipe.yaml
  CHANGELOG.md
  setup.py
  tests/core/test_axes.py
  tests/core/test_dump_restore.py
  tests/core/test_entities.py
  tests/core/test_holders.py
  tests/core/test_reforms.py
  tests/core/test_simulation_builder.py
  tests/core/test_simulations.py
  tests/core/variables/test_variables.py
  tests/fixtures/entities.py
  tests/fixtures/yaml_tests/test_success.yml
  tests/fixtures/yaml_tests/test_with_anchors.yaml
  tests/fixtures/yaml_tests/test_with_extension.yaml
  tests/web_api/test_calculate.py
  tests/web_api/test_entities.py
  tests/web_api/test_spec.py
  tests/web_api/test_trace.py
  tests/web_api/test_variables.py
Labels: kind:test

#1300 refactor: consolidate commons module types
  CHANGELOG.md
  openfisca_core/commons/__init__.py
  openfisca_core/commons/formulas.py
  openfisca_core/commons/misc.py
  openfisca_core/commons/rates.py
  openfisca_core/commons/types.py
  openfisca_core/types.py
  setup.py
Labels: kind:refactor

#1301 refactor: consolidate tracers module types
  CHANGELOG.md
  openfisca_core/tracers/__init__.py
  openfisca_core/tracers/computation_log.py
  openfisca_core/tracers/flat_trace.py
  openfisca_core/tracers/full_tracer.py
  openfisca_core/tracers/simple_tracer.py
  openfisca_core/tracers/trace_node.py
  openfisca_core/tracers/types.py
  openfisca_core/types.py
  setup.py
Labels: kind:refactor

#1302 refactor: consolidate periods module types
  CHANGELOG.md
  openfisca_core/periods/__init__.py
  openfisca_core/periods/_parsers.py
  openfisca_core/periods/config.py
  openfisca_core/periods/date_unit.py
  openfisca_core/periods/helpers.py
  openfisca_core/periods/instant_.py
  openfisca_core/periods/period_.py
  openfisca_core/periods/types.py
  openfisca_core/types.py
  setup.py
Labels: kind:refactor

#1325 docs: fix ambiguous doc refs
  CHANGELOG.md
  openfisca_core/populations/_core_population.py
  openfisca_core/reforms/reform.py
  setup.py
Labels: kind:docs
